// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hod.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type QueryRequest struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_597a1145af8a0706, []int{0}
}
func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (m *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(m, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type QueryResponse struct {
	Variable             []string `protobuf:"bytes,1,rep,name=variable,proto3" json:"variable,omitempty"`
	Rows                 []*Row   `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	Count                int64    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Elapsed              int64    `protobuf:"varint,4,opt,name=elapsed,proto3" json:"elapsed,omitempty"`
	Errors               []string `protobuf:"bytes,5,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryResponse) Reset()         { *m = QueryResponse{} }
func (m *QueryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()    {}
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_597a1145af8a0706, []int{1}
}
func (m *QueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResponse.Unmarshal(m, b)
}
func (m *QueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResponse.Marshal(b, m, deterministic)
}
func (m *QueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponse.Merge(m, src)
}
func (m *QueryResponse) XXX_Size() int {
	return xxx_messageInfo_QueryResponse.Size(m)
}
func (m *QueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponse proto.InternalMessageInfo

func (m *QueryResponse) GetVariable() []string {
	if m != nil {
		return m.Variable
	}
	return nil
}

func (m *QueryResponse) GetRows() []*Row {
	if m != nil {
		return m.Rows
	}
	return nil
}

func (m *QueryResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *QueryResponse) GetElapsed() int64 {
	if m != nil {
		return m.Elapsed
	}
	return 0
}

func (m *QueryResponse) GetErrors() []string {
	if m != nil {
		return m.Errors
	}
	return nil
}

type Row struct {
	Uris                 []*URI   `protobuf:"bytes,1,rep,name=uris,proto3" json:"uris,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Row) Reset()         { *m = Row{} }
func (m *Row) String() string { return proto.CompactTextString(m) }
func (*Row) ProtoMessage()    {}
func (*Row) Descriptor() ([]byte, []int) {
	return fileDescriptor_597a1145af8a0706, []int{2}
}
func (m *Row) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Row.Unmarshal(m, b)
}
func (m *Row) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Row.Marshal(b, m, deterministic)
}
func (m *Row) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Row.Merge(m, src)
}
func (m *Row) XXX_Size() int {
	return xxx_messageInfo_Row.Size(m)
}
func (m *Row) XXX_DiscardUnknown() {
	xxx_messageInfo_Row.DiscardUnknown(m)
}

var xxx_messageInfo_Row proto.InternalMessageInfo

func (m *Row) GetUris() []*URI {
	if m != nil {
		return m.Uris
	}
	return nil
}

type URI struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *URI) Reset()         { *m = URI{} }
func (m *URI) String() string { return proto.CompactTextString(m) }
func (*URI) ProtoMessage()    {}
func (*URI) Descriptor() ([]byte, []int) {
	return fileDescriptor_597a1145af8a0706, []int{3}
}
func (m *URI) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_URI.Unmarshal(m, b)
}
func (m *URI) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_URI.Marshal(b, m, deterministic)
}
func (m *URI) XXX_Merge(src proto.Message) {
	xxx_messageInfo_URI.Merge(m, src)
}
func (m *URI) XXX_Size() int {
	return xxx_messageInfo_URI.Size(m)
}
func (m *URI) XXX_DiscardUnknown() {
	xxx_messageInfo_URI.DiscardUnknown(m)
}

var xxx_messageInfo_URI proto.InternalMessageInfo

func (m *URI) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *URI) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryRequest)(nil), "proto.QueryRequest")
	proto.RegisterType((*QueryResponse)(nil), "proto.QueryResponse")
	proto.RegisterType((*Row)(nil), "proto.Row")
	proto.RegisterType((*URI)(nil), "proto.URI")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HodDBClient is the client API for HodDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HodDBClient interface {
	ExecuteQuery(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
}

type hodDBClient struct {
	cc *grpc.ClientConn
}

func NewHodDBClient(cc *grpc.ClientConn) HodDBClient {
	return &hodDBClient{cc}
}

func (c *hodDBClient) ExecuteQuery(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, "/proto.HodDB/ExecuteQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HodDBServer is the server API for HodDB service.
type HodDBServer interface {
	ExecuteQuery(context.Context, *QueryRequest) (*QueryResponse, error)
}

func RegisterHodDBServer(s *grpc.Server, srv HodDBServer) {
	s.RegisterService(&_HodDB_serviceDesc, srv)
}

func _HodDB_ExecuteQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HodDBServer).ExecuteQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HodDB/ExecuteQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HodDBServer).ExecuteQuery(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HodDB_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.HodDB",
	HandlerType: (*HodDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteQuery",
			Handler:    _HodDB_ExecuteQuery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hod.proto",
}

func init() { proto.RegisterFile("hod.proto", fileDescriptor_597a1145af8a0706) }

var fileDescriptor_597a1145af8a0706 = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xc1, 0x4a, 0xf3, 0x40,
	0x14, 0x85, 0x49, 0xd3, 0xf4, 0xff, 0x73, 0x6d, 0x37, 0x63, 0x91, 0xa1, 0x14, 0x09, 0x41, 0x21,
	0xb8, 0x68, 0xb0, 0xae, 0x74, 0x29, 0x0a, 0x76, 0xe9, 0x48, 0x77, 0x6e, 0xa6, 0xcd, 0xa5, 0x0d,
	0xc4, 0xdc, 0x74, 0x26, 0xd3, 0xea, 0xd6, 0x57, 0xe8, 0xa3, 0xf9, 0x0a, 0x3e, 0x88, 0x64, 0x26,
	0x5a, 0x5d, 0x0d, 0xdf, 0xe1, 0xc0, 0x37, 0xf7, 0x40, 0xb8, 0xa6, 0x6c, 0x52, 0x29, 0xaa, 0x89,
	0x05, 0xf6, 0x19, 0x8d, 0x57, 0x44, 0xab, 0x02, 0x53, 0x59, 0xe5, 0xa9, 0x2c, 0x4b, 0xaa, 0x65,
	0x9d, 0x53, 0xa9, 0x5d, 0x29, 0x3e, 0x83, 0xfe, 0xa3, 0x41, 0xf5, 0x26, 0x70, 0x63, 0x50, 0xd7,
	0x6c, 0x08, 0xc1, 0xa6, 0x61, 0xee, 0x45, 0x5e, 0x12, 0x0a, 0x07, 0xf1, 0xde, 0x83, 0x41, 0x5b,
	0xd3, 0x15, 0x95, 0x1a, 0xd9, 0x08, 0xfe, 0x6f, 0xa5, 0xca, 0xe5, 0xa2, 0x40, 0xee, 0x45, 0x7e,
	0x12, 0x8a, 0x1f, 0x66, 0xa7, 0xd0, 0x55, 0xb4, 0xd3, 0xbc, 0x13, 0xf9, 0xc9, 0xd1, 0x14, 0x9c,
	0x69, 0x22, 0x68, 0x27, 0x6c, 0xde, 0x38, 0x96, 0x64, 0xca, 0x9a, 0xfb, 0x91, 0x97, 0xf8, 0xc2,
	0x01, 0xe3, 0xf0, 0x0f, 0x0b, 0x59, 0x69, 0xcc, 0x78, 0xd7, 0xe6, 0xdf, 0xc8, 0x4e, 0xa0, 0x87,
	0x4a, 0x91, 0xd2, 0x3c, 0xb0, 0xa6, 0x96, 0xe2, 0x73, 0xf0, 0x05, 0xed, 0x1a, 0x9d, 0x51, 0xb9,
	0xb6, 0xdf, 0x38, 0xe8, 0xe6, 0x62, 0x26, 0x6c, 0x1e, 0x5f, 0x83, 0x3f, 0x17, 0x33, 0x36, 0x86,
	0xb0, 0x94, 0x2f, 0xa8, 0x2b, 0xb9, 0xc4, 0xf6, 0xba, 0x43, 0xd0, 0xfc, 0x69, 0x2b, 0x0b, 0x83,
	0xbc, 0xe3, 0xee, 0xb6, 0x30, 0x7d, 0x86, 0xe0, 0x81, 0xb2, 0xbb, 0x5b, 0xf6, 0x04, 0xfd, 0xfb,
	0x57, 0x5c, 0x9a, 0x1a, 0xed, 0x0c, 0xec, 0xb8, 0xb5, 0xfc, 0xde, 0x6e, 0x34, 0xfc, 0x1b, 0xba,
	0xa5, 0x62, 0xfe, 0xfe, 0xf1, 0xb9, 0xef, 0xb0, 0x78, 0x90, 0x6e, 0x2f, 0xd3, 0x35, 0x65, 0xa9,
	0x9d, 0xf4, 0xc6, 0xbb, 0x58, 0xf4, 0x6c, 0xfd, 0xea, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x97, 0x8b,
	0xc3, 0x94, 0xb4, 0x01, 0x00, 0x00,
}
